spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zsl1426
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  type-aliases-package: com.zsl.order.dao
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  check-config-location: true